source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'
use_frameworks!

project 'ImageLoaderExample'
workspace '../ImageLoader'

target 'ImageLoaderExample' do
  pod 'ImageLoader', '0.0.1'
end